spring:
  application:
    name: account-id-system
  webflux:
    base-path: /api/account-id-system
  config:
    import:
      - 'classpath:r2dbc.yml'
      - 'classpath:liquibase.yml'
      - 'classpath:redis.yml'